spring.application.name=ApiCursoSpringBoot
spring.datasource.url=jdbc:mysql://localhost:3306/api_springboot
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.port=9000
